# Generated by Django 5.2.5 on 2025-08-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JiraTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('issue_type_id', models.CharField(default='10003', max_length=10)),
                ('priority_id', models.CharField(default='3', max_length=10)),
                ('labels', models.JSONField(default=list)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
